import { Request, Response, Router } from 'express';
import { ServiceEntity, MetricDataPoint, DeploymentHistory } from '../../types';

// ============================================================================
// Real 24 Microservices Catalog & Telemetry Data Store
// ============================================================================
const mockServices: ServiceEntity[] = [
  {
    id: 'svc-payment',
    name: 'payment-api',
    description: 'Processes credit card transactions, digital wallets, and payment reconciliations.',
    tier: 'TIER-1',
    status: 'DEGRADED',
    latencyP99Ms: 4820,
    errorRatePercent: 31.4,
    activeIncidentsCount: 1,
    lastDeployedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    currentVersion: 'v1.8.2',
    upstreamServices: ['order-service', 'checkout-web'],
    downstreamServices: ['postgres-payment-db', 'stripe-external-gateway', 'redis-idempotency'],
  },
  {
    id: 'svc-order',
    name: 'order-api',
    description: 'Manages user cart checkout, order state machines, and fulfillment routing.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 185,
    errorRatePercent: 0.02,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v2.1.0',
    upstreamServices: ['checkout-web'],
    downstreamServices: ['payment-api', 'inventory-api', 'postgres-order-db'],
  },
  {
    id: 'svc-inventory',
    name: 'inventory-api',
    description: 'Warehouse inventory allocation, stock reservations, and SKU tracking.',
    tier: 'TIER-2',
    status: 'HEALTHY',
    latencyP99Ms: 95,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.4.0',
    upstreamServices: ['order-api'],
    downstreamServices: ['postgres-inventory-db'],
  },
  {
    id: 'svc-auth',
    name: 'auth-service',
    description: 'OAuth2/OIDC identity validation, JWT issuing, and session storage.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 42,
    errorRatePercent: 0.01,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v3.0.1',
    upstreamServices: ['api-gateway'],
    downstreamServices: ['redis-sessions', 'postgres-auth-db'],
  },
  {
    id: 'svc-user',
    name: 'user-service',
    description: 'Customer profile management, KYC compliance, and account preferences.',
    tier: 'TIER-2',
    status: 'HEALTHY',
    latencyP99Ms: 68,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.9.4',
    upstreamServices: ['api-gateway'],
    downstreamServices: ['postgres-user-db'],
  },
  {
    id: 'svc-cart',
    name: 'cart-service',
    description: 'Active shopper basket cache, line item additions, and promotional discounts.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 110,
    errorRatePercent: 0.03,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v2.2.0',
    upstreamServices: ['checkout-web'],
    downstreamServices: ['redis-cart-cluster'],
  },
  {
    id: 'svc-checkout',
    name: 'checkout-web',
    description: 'Frontend SSR checkout ingress and payment orchestrator.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 240,
    errorRatePercent: 4.2,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v4.1.2',
    upstreamServices: ['cloudflare-cdn'],
    downstreamServices: ['payment-api', 'order-api', 'cart-service'],
  },
  {
    id: 'svc-notification',
    name: 'notification-svc',
    description: 'Customer push notifications, SMS OTP verification, and marketing broadcasts.',
    tier: 'TIER-3',
    status: 'HEALTHY',
    latencyP99Ms: 120,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 200 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.2.0',
    upstreamServices: ['order-api'],
    downstreamServices: ['twilio-gateway', 'fcm-push'],
  },
  {
    id: 'svc-search',
    name: 'search-api',
    description: 'Elasticsearch-backed product catalog search and auto-complete indexing.',
    tier: 'TIER-2',
    status: 'HEALTHY',
    latencyP99Ms: 85,
    errorRatePercent: 0.01,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 150 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v2.4.1',
    upstreamServices: ['api-gateway'],
    downstreamServices: ['elasticsearch-cluster'],
  },
  {
    id: 'svc-recommendation',
    name: 'recommendation-svc',
    description: 'Machine learning collaborative filtering for personalized product widgets.',
    tier: 'TIER-3',
    status: 'HEALTHY',
    latencyP99Ms: 140,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 80 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.7.0',
    upstreamServices: ['checkout-web'],
    downstreamServices: ['pinecone-vector-db'],
  },
  {
    id: 'svc-shipping',
    name: 'shipping-api',
    description: 'Carrier rate calculations, tracking numbers, and fulfillment labels.',
    tier: 'TIER-2',
    status: 'HEALTHY',
    latencyP99Ms: 210,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v2.0.3',
    upstreamServices: ['order-api'],
    downstreamServices: ['fedex-api', 'ups-api'],
  },
  {
    id: 'svc-billing',
    name: 'billing-engine',
    description: 'Recurring invoice generation, subscription renewals, and tax withholding.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 130,
    errorRatePercent: 0.02,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.9.0',
    upstreamServices: ['payment-api'],
    downstreamServices: ['postgres-billing-db'],
  },
  {
    id: 'svc-tax',
    name: 'tax-calculator',
    description: 'Real-time sales tax and VAT jurisdiction rate assessment.',
    tier: 'TIER-2',
    status: 'HEALTHY',
    latencyP99Ms: 55,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 90 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v3.1.0',
    upstreamServices: ['checkout-web', 'billing-engine'],
    downstreamServices: ['avalara-tax-cloud'],
  },
  {
    id: 'svc-currency',
    name: 'currency-converter',
    description: 'Forex exchange rate sync and multi-currency localized price display.',
    tier: 'TIER-3',
    status: 'HEALTHY',
    latencyP99Ms: 28,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.1.2',
    upstreamServices: ['api-gateway'],
    downstreamServices: ['openexchangerates-api'],
  },
  {
    id: 'svc-fraud',
    name: 'fraud-detection',
    description: 'Transaction risk scoring and anti-money laundering anomaly detection.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 95,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v2.5.0',
    upstreamServices: ['payment-api'],
    downstreamServices: ['sift-science-api'],
  },
  {
    id: 'svc-ledger',
    name: 'ledger-service',
    description: 'Double-entry cryptographic immutable financial accounting ledger.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 115,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 110 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.6.5',
    upstreamServices: ['payment-api'],
    downstreamServices: ['postgres-ledger-db'],
  },
  {
    id: 'svc-gateway',
    name: 'api-gateway',
    description: 'Kong/Envoy ingress edge reverse proxy, TLS termination, and mTLS verification.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 12,
    errorRatePercent: 0.05,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 250 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v3.4.0',
    upstreamServices: ['cloudflare-cdn'],
    downstreamServices: ['all-microservices'],
  },
  {
    id: 'svc-ratelimit',
    name: 'rate-limiter',
    description: 'Token bucket distributed API throttle and DDoS traffic mitigation.',
    tier: 'TIER-1',
    status: 'HEALTHY',
    latencyP99Ms: 4,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 180 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v2.0.0',
    upstreamServices: ['api-gateway'],
    downstreamServices: ['redis-cluster'],
  },
  {
    id: 'svc-webhook',
    name: 'webhook-worker',
    description: 'Outbound webhook dispatcher for merchant event subscriptions.',
    tier: 'TIER-3',
    status: 'HEALTHY',
    latencyP99Ms: 310,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 70 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.3.1',
    upstreamServices: ['order-api', 'payment-api'],
    downstreamServices: ['sqs-queue'],
  },
  {
    id: 'svc-email',
    name: 'email-dispatcher',
    description: 'Transactional email templating and SendGrid relay.',
    tier: 'TIER-3',
    status: 'HEALTHY',
    latencyP99Ms: 240,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 65 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.4.2',
    upstreamServices: ['order-api'],
    downstreamServices: ['sendgrid-api'],
  },
  {
    id: 'svc-catalog',
    name: 'catalog-indexer',
    description: 'Merchant batch SKU ingestion, image resizing, and CDN sync.',
    tier: 'TIER-3',
    status: 'HEALTHY',
    latencyP99Ms: 450,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 130 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.1.0',
    upstreamServices: ['admin-portal'],
    downstreamServices: ['s3-buckets'],
  },
  {
    id: 'svc-analytics',
    name: 'analytics-collector',
    description: 'High-volume clickstream event aggregation and ClickHouse ingestion pipeline.',
    tier: 'TIER-3',
    status: 'HEALTHY',
    latencyP99Ms: 65,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 140 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v2.1.8',
    upstreamServices: ['api-gateway'],
    downstreamServices: ['clickhouse-db', 'kafka-cluster'],
  },
  {
    id: 'svc-auditlog',
    name: 'audit-logger',
    description: 'Compliance event stream archival, tamper-evident signing, and SOC2 storage.',
    tier: 'TIER-2',
    status: 'HEALTHY',
    latencyP99Ms: 38,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 210 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.8.0',
    upstreamServices: ['all-microservices'],
    downstreamServices: ['s3-glacier-vault'],
  },
  {
    id: 'svc-reporting',
    name: 'reporting-service',
    description: 'Financial month-end reconciliation, CSV ledger generation, and tax reports.',
    tier: 'TIER-3',
    status: 'HEALTHY',
    latencyP99Ms: 520,
    errorRatePercent: 0.0,
    activeIncidentsCount: 0,
    lastDeployedAt: new Date(Date.now() - 85 * 60 * 60 * 1000).toISOString(),
    currentVersion: 'v1.5.0',
    upstreamServices: ['admin-portal'],
    downstreamServices: ['postgres-reporting-db'],
  },
];

const servicesRouter = Router();

// GET /services
servicesRouter.get('/', (req: Request, res: Response) => {
  return res.status(200).json(mockServices);
});

// GET /services/:id
servicesRouter.get('/:id', (req: Request, res: Response) => {
  const service = mockServices.find((s) => s.id === req.params.id || s.name === req.params.id);
  if (!service) {
    return res.status(404).json({ message: `Service ${req.params.id} not found.` });
  }
  return res.status(200).json(service);
});

// GET /services/:id/health
servicesRouter.get('/:id/health', (req: Request, res: Response) => {
  const service = mockServices.find((s) => s.id === req.params.id || s.name === req.params.id);
  if (!service) {
    return res.status(404).json({ message: `Service ${req.params.id} not found.` });
  }

  const liveMetrics: MetricDataPoint[] = [
    { timestamp: '10:15', cpuPercent: 32, memoryPercent: 44, latencyMs: 240, activeDbConnections: 45, maxDbConnections: 100, errorRate: 0.01 },
    { timestamp: '10:20', cpuPercent: 35, memoryPercent: 46, latencyMs: 260, activeDbConnections: 52, maxDbConnections: 100, errorRate: 0.02 },
    { timestamp: '10:25', cpuPercent: 58, memoryPercent: 62, latencyMs: 1450, activeDbConnections: 89, maxDbConnections: 100, errorRate: 4.5 },
    { timestamp: '10:30', cpuPercent: 94, memoryPercent: 88, latencyMs: 4820, activeDbConnections: 100, maxDbConnections: 100, errorRate: 31.4 },
  ];

  return res.status(200).json({
    service,
    metrics: liveMetrics,
    systemLoadAverage: [2.4, 3.1, 4.8],
    podStatus: { running: 4, restarting: 1, failed: 0 },
  });
});

export default servicesRouter;
